### ISSUE TITLE
Bot isn't starting

### ISSUE THREAD

**Issue by danimesq** [mashirochan/MashiBot#3]
---
## | Welcome Mashiro-chan | MashiBot! |

info  starting server
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
undefined:0

I get this message when start:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (/root/MashiBot/parser.js:14:21)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/MashiBot/main.js:173:16)
    at Module._compile (module.js:430:26)

**Comment by danimesq** [comment]
@mashirochan
